<<<<<<< HEAD
import "./globals.css";

export const metadata = {
  title: "Eco Tourism",
  description: "Discover and share stunning eco-friendly travel locations.",
  icons: {
    icon: "/favicon.png",
  },
=======
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> 31186843fa8a9845df05159cbb06f7eae7df9cff
};

export default function RootLayout({
  children,
<<<<<<< HEAD
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
=======
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <main style={{ minHeight: "80vh" }}>{children}</main>
        
      </body>
>>>>>>> 31186843fa8a9845df05159cbb06f7eae7df9cff
    </html>
  );
}
